<a href="https://colab.research.google.com/github/sanjanabalan84-glitch/ML-AI-PROJECT/blob/main/Day_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df=sns.load_dataset("titanic")

In [ ]:
df.shape

(891, 15)

In [ ]:
df.size

13365

In [ ]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [ ]:
df.isnull().sum() #to identify missing values

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df_clean=df.drop(columns=['deck']) #to remove columns
df_clean.shape

(891, 14)

In [ ]:
df.dropna(subset=['embarked','embark_town'],inplace=True) #only removing the mentioned name
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [ ]:
age_mean=df['age'].mean()
df['age']=df['age'].fillna(age_mean)

In [ ]:
df['family_size']=df['sibsp']+df['parch']
df['age_group']=np.where(df['age']<18,"child","Adult")
df['fare_per_person']=df['fare']/(df['family_size']+1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   survived         889 non-null    int64
 1   pclass           889 non-null    int64
 2   sex              889 non-null    object
 3   age              889 non-null    float64
 4   sibsp            889 non-null    int64
 5   parch            889 non-null    int64
 6   fare             889 non-null    float64
 7   embarked         889 non-null    object
 8   class            889 non-null    category
 9   who              889 non-null    object
 10  adult_male       889 non-null    bool
 11  deck             201 non-null    category
 12  embark_town      889 non-null    object
 13  alive            889 non-null    object
 14  alone            889 non-null    bool
 15  family-size      889 non-null    int64
 16  age_group        889 non-null    object
 17  family_size      889 non-null    int64
 18  fare_per_person  889 non-null    float64
dtypes: bool(2), category(2), float64(3), int64(6), object(6)
memory usage: 115.1+ KB

In [ ]:
df.rename(columns={'pclass':'passenger_class'},inplace=True)

In [ ]:
df[df['age']>df['age'].mean()]

,survived,passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family-size,age_group,family_size,fare_per_person
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,1,35.641650
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,Adult,1,26.550000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,Adult,0,8.050000
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True,0,Adult,0,51.862500
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,0,Adult,0,26.550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True,0,Adult,0,9.000000
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,1,41.579150
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,0,Adult,0,7.895800
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,5,Adult,5,4.854167
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0,Adult,0,7.750000

In [ ]:
df[(df['sex']=='female')&(df['passenger_class']==1)] #how many female are in the first class # logical operation

,survived,passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family-size,age_group,family_size,fare_per_person
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,1,35.641650
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,Adult,1,26.550000
11,1,1,female,58.000000,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True,0,Adult,0,26.550000
31,1,1,female,29.642093,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False,1,Adult,1,73.260400
52,1,1,female,49.000000,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False,1,Adult,1,38.364600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.000000,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False,2,Adult,2,54.955567
862,1,1,female,48.000000,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True,0,Adult,0,25.929200
871,1,1,female,47.000000,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False,2,Adult,2,17.518067
879,1,1,female,56.000000,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,1,41.579150
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0,Adult,0,30.000000

In [ ]:
df[df['survived']==1] #individual only

,survived,passenger_class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family-size,age_group,family_size,fare_per_person
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,1,35.64165
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,Adult,0,7.92500
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,Adult,1,26.55000
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False,2,Adult,2,3.71110
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False,1,child,1,15.03540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True,0,child,0,7.22500
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False,1,Adult,1,41.57915
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False,1,Adult,1,13.00000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,0,Adult,0,30.00000
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0,Adult,0,30.00000

In [ ]:
df.groupby('sex')['survived'].mean()

sex
female    0.740385
male      0.188908
Name: survived, dtype: float64

In [ ]:
df.groupby('class')['fare'].mean()

/tmp/ipython-input-4105422611.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('class')['fare'].mean()

class
First     84.193516
Second    20.662183
Third     13.675550
Name: fare, dtype: float64

In [ ]:
df.corr(numeric_only=True)

,survived,passenger_class,age,sibsp,parch,fare,adult_male,alone,family-size,family_size,fare_per_person
survived,1.000000,-0.335549,-0.074513,-0.034040,0.083151,0.255290,-0.555520,-0.206207,0.018277,0.018277,0.217902
passenger_class,-0.335549,1.000000,-0.328256,0.081656,0.016824,-0.548193,0.090098,0.138553,0.064221,0.064221,-0.482024
age,-0.074513,-0.328256,1.000000,-0.231908,-0.178013,0.088780,0.258793,0.177445,-0.247459,-0.247459,0.136787
sibsp,-0.034040,0.081656,-0.231908,1.000000,0.414542,0.160887,-0.255401,-0.584186,0.890654,0.890654,-0.093211
parch,0.083151,0.016824,-0.178013,0.414542,1.000000,0.217532,-0.351945,-0.583112,0.782988,0.782988,-0.067422
fare,0.255290,-0.548193,0.088780,0.160887,0.217532,1.000000,-0.179851,-0.274079,0.218658,0.218658,0.840902
adult_male,-0.555520,0.090098,0.258793,-0.255401,-0.351945,-0.179851,1.000000,0.407992,-0.350419,-0.350419,-0.078503
alone,-0.206207,0.138553,0.177445,-0.584186,-0.583112,-0.274079,0.407992,1.000000,-0.690654,-0.690654,0.042706
family-size,0.018277,0.064221,-0.247459,0.890654,0.782988,0.218658,-0.350419,-0.690654,1.000000,1.000000,-0.097399
family_size,0.018277,0.064221,-0.247459,0.890654,0.782988,0.218658,-0.350419,-0.690654,1.000000,1.000000,-0.097399
fare_per_person,0.217902,-0.482024,0.136787,-0.093211,-0.067422,0.840902,-0.078503,0.042706,-0.097399,-0.097399,1.000000

In [ ]:
df=sns.load_dataset("tips")

In [ ]:
df.shape

(244, 7)

In [ ]:
df.size

1708

In [ ]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
df['tip'].mean()

np.float64(2.99827868852459)

In [ ]:
df['tip'].median()

2.9

In [ ]:
df['tip_percentage']=(df['tip']*100)/(df['total_bill'])
df

,total_bill,tip,sex,smoker,day,time,size,tip_percentage,high_spender
0,16.99,1.01,Female,No,Sun,Dinner,2,5.944673,0
1,10.34,1.66,Male,No,Sun,Dinner,3,16.054159,0
2,21.01,3.50,Male,No,Sun,Dinner,3,16.658734,1
3,23.68,3.31,Male,No,Sun,Dinner,2,13.978041,1
4,24.59,3.61,Female,No,Sun,Dinner,4,14.680765,1
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.392697,1
240,27.18,2.00,Female,Yes,Sat,Dinner,2,7.358352,1
241,22.67,2.00,Male,Yes,Sat,Dinner,2,8.822232,1
242,17.82,1.75,Male,No,Sat,Dinner,2,9.820426,0
243,18.78,3.00,Female,No,Thur,Dinner,2,15.974441,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   total_bill      244 non-null    float64
 1   tip             244 non-null    float64
 2   sex             244 non-null    category
 3   smoker          244 non-null    category
 4   day             244 non-null    category
 5   time            244 non-null    category
 6   size            244 non-null    int64
 7   tip_percentage  244 non-null    float64
dtypes: category(4), float64(3), int64(1)
memory usage: 9.3 KB

In [ ]:
df['high_spender']=np.where(df['total_bill']>df["total_bill"].mean(),1,0) # conditional selection

In [ ]:
df["total_bill"]>30  #only seeing the columns

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df['tip_percentage']>20

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: tip_percentage, Length: 244, dtype: bool

In [ ]:
df.groupby('sex')['tip'].mean()

/tmp/ipython-input-3407121299.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')['tip'].mean()

sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64

In [ ]:
df.groupby('day')['total_bill'].mean()

/tmp/ipython-input-1881343769.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('day')['total_bill'].mean()

day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [ ]:
df.groupby('smoker')['tip_percentage'].mean()

/tmp/ipython-input-3494168819.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('smoker')['tip_percentage'].mean()

smoker
Yes    0.152638
No     0.150011
Name: tip_percentage, dtype: float64

In [ ]:
df.corr(numeric_only=True)

                total_bill       tip      size  tip_percentage  high_spender
total_bill        1.000000  0.675734  0.598315       -0.290648      0.787342
tip               0.675734  1.000000  0.489299        0.406578      0.554292
size              0.598315  0.489299  1.000000       -0.106626      0.497736
tip_percentage   -0.290648  0.406578 -0.106626        1.000000     -0.211238
high_spender      0.787342  0.554292  0.497736       -0.211238      1.000000

In [ ]:
arr1=np.arange(1,17)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
np.reshape(arr1,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arr2=np.arange(1,7)

In [ ]:
arr2

array([1, 2, 3, 4, 5, 6])

In [ ]:
x=np.array([1,2,3,4,5,6])
x[x%2==0]=-1
x

array([ 1, -1,  3, -1,  5, -1])

In [ ]:
y=np.array([10,20,30,40,50])
y

array([10, 20, 30, 40, 50])

In [ ]:
z=np.mean(y)
z

np.float64(30.0)

In [ ]:
t=np.std(y)
t

np.float64(14.142135623730951)

In [ ]:
d=(y-(z))/(t)
d

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [ ]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0][1]

np.int64(2)

In [ ]:
a[1][1]

np.int64(5)

In [ ]:
a[2][0]

np.int64(7)

In [ ]:
a[2:]

array([[7, 8, 9]])

In [ ]:
a[1:,:2]

array([[4, 5],
       [7, 8]])

In [ ]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
df=sns.load_dataset("penguins")

In [ ]:
df.shape

(344, 7)

In [ ]:
df.size

2408

In [ ]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
df.isnull().sum() #to identify missing values

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [ ]:
df.dtypes

species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

In [ ]:
bill_length_mm=df['bill_length_mm'].mean()
df['bill_length_mm']=df['bill_length_mm'].fillna(bill_length_mm)
df['bill_depth_mm']

0      18.7
1      17.4
2      18.0
3       NaN
4      19.3
       ...
339     NaN
340    14.3
341    15.7
342    14.8
343    16.1
Name: bill_depth_mm, Length: 344, dtype: float64

In [ ]:
bill_depth_mm=df['bill_depth_mm'].mean()
df['bill_depth_mm']=df['bill_depth_mm'].fillna(bill_depth_mm)
df['bill_depth_mm']

0      18.70000
1      17.40000
2      18.00000
3      17.15117
4      19.30000
         ...
339    17.15117
340    14.30000
341    15.70000
342    14.80000
343    16.10000
Name: bill_depth_mm, Length: 344, dtype: float64

In [31]:
flip_len=df['flipper_length_mm'].mean()
df['flipper_length_mm']=df['flipper_length_mm'].fillna(flip_len)
df['flipper_length_mm']

0      181.000000
1      186.000000
2      195.000000
3      200.915205
4      193.000000
          ...
339    200.915205
340    215.000000
341    222.000000
342    212.000000
343    213.000000
Name: flipper_length_mm, Length: 344, dtype: float64

In [32]:
body_mass=df['body_mass_g'].mean()
df['body_mass_g']=df['body_mass_g'].fillna(body_mass)
df['body_mass_g']

0      3750.000000
1      3800.000000
2      3250.000000
3      4201.754386
4      3450.000000
          ...
339    4201.754386
340    4850.000000
341    5750.000000
342    5200.000000
343    5400.000000
Name: body_mass_g, Length: 344, dtype: float64

In [35]:
df.groupby('species')['bill_length_mm'].mean()

species
Adelie       38.825144
Chinstrap    48.833824
Gentoo       47.475983
Name: bill_length_mm, dtype: float64

In [36]:
df.groupby('species')['body_mass_g'].mean()

species
Adelie       3703.958910
Chinstrap    3733.088235
Gentoo       5068.965761
Name: body_mass_g, dtype: float64

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [41]:
df['body_mass_g'].mean()

np.float64(4201.754385964912)

In [43]:
df['body_mass_g'].median()

4050.0

In [44]:
df[df['flipper_length_mm']==1]

Empty DataFrame
Columns: [species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex]
Index: []